import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { Provider } from "@/provider";
import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";
import BackToTop from "@/components/shared/back-to-top";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className=" scroll-smooth" lang="en">
      <body className={manrope.className}>
        <Provider defaultTheme="dark">
          <Header />
          {children}
          <BackToTop />
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
